#indica la version de Docker Compose utilizada
version: '3.7'
#Bloque de servicios, indica los contenedores a utilizar.
services:

  eurekaserver: #nombre del servicio
    image: enmanuelcruzdejesus/eurekaserver #imagen utilizada.
    ports: #puertos que estaran expuestos.
      - 8761:8761
    expose:
      - 8761
    environment: #variable de ambiente
      - server.port=8761
    networks: #red para conectar los equipos.
      - main-net
    volumes:
      - my-vol:/tmp/

  gatewayserver: #nombre del servicio
    image: enmanuelcruzdejesus/gatewayserver #imagen utilizada.
    ports: #puertos que estaran expuestos.
      - 8080:8080
    expose:
      - 8080
    environment: #variable de ambiente
      - server.port=8080
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka
      - zuul.routes.microservicio-usuario.url=http://microservicio-usuario:9090
    networks: #red para conectar los equipos.
      - main-net
    volumes:
      - my-vol:/tmp/
    depends_on: #indica que primero debe subir los servicios indicados.
      - eurekaserver
      - microservicio-usuario1
      - microservicio-usuario2
      - microservicio-usuario3

  base-datos-app-compras:
    image: mysql
    ports:
      - 33006:3306
    environment:
      - MYSQL_ROOT_PASSWORD=entrada01
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=entrada01
      - MYSQL_DATABASE=ordersdb
    volumes:   #volumen de datos utilizado.
      - ~/datadir_mysql:/var/lib/mysql
    networks:
      -  main-net

  base-datos-app-usuarios:
    image: mysql
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=entrada01
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=entrada01
      - MYSQL_DATABASE=usersdb
    volumes:   #volumen de datos utilizado.
      - ~/usersdb:/var/lib/mysql
    networks:
      -  main-net

  microservicio-compras: #nombre del servicio
    image: enmanuelcruzdejesus/microservicio-compras #imagen utilizada.
    ports: #puertos que estaran expuestos.
      - 8181:8181
    environment: #variable de ambiente
      - spring.datasource.url=jdbc:mysql://base-datos-app-compras:3306/ordersdb
      - spring.datasource.username=root
      - spring.datasource.password=entrada01
      - server.port=8181
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka
    networks: #red para conectar los equipos.
      - main-net
    volumes:
      - my-vol:/tmp/
    depends_on: #indica que primero debe subir los servicios indicados.
      - base-datos-app-compras
      - eurekaserver

  microservicio-usuario1: #nombre del servicio
    image: enmanuelcruzdejesus/microservicio-usuario #imagen utilizada.
    ports: #puertos que estaran expuestos.
      - 9090:9090
    expose:
      - 9090
    environment: #variable de ambiente
      - spring.datasource.url=jdbc:mysql://base-datos-app-usuarios:3306/usersdb
      - spring.datasource.username=root
      - spring.datasource.password=entrada01
      - server.port=9090
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka
    networks: #red para conectar los equipos.
      - main-net
    volumes:
      - my-vol:/tmp/
    depends_on: #indica que primero debe subir los servicios indicados.
      - base-datos-app-usuarios
      - eurekaserver

  microservicio-usuario2: #nombre del servicio
    image: enmanuelcruzdejesus/microservicio-usuario #imagen utilizada.
    ports: #puertos que estaran expuestos.
      - 9191:9191
    expose:
      - 9191
    environment: #variable de ambiente
      - spring.datasource.url=jdbc:mysql://base-datos-app-usuarios:3306/usersdb
      - spring.datasource.username=root
      - spring.datasource.password=entrada01
      - server.port=9090
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka
    networks: #red para conectar los equipos.
      - main-net
    volumes:
      - my-vol:/tmp/
    depends_on: #indica que primero debe subir los servicios indicados.
      - base-datos-app-usuarios
      - eurekaserver



  microservicio-usuario3: #nombre del servicio
    image: enmanuelcruzdejesus/microservicio-usuario #imagen utilizada.
    ports: #puertos que estaran expuestos.
      - 9292:9292
    expose:
      - 9292
    environment: #variable de ambiente
      - spring.datasource.url=jdbc:mysql://base-datos-app-usuarios:3306/usersdb
      - spring.datasource.username=root
      - spring.datasource.password=entrada01
      - server.port=9090
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka
    networks: #red para conectar los equipos.
      - main-net
    volumes:
      - my-vol:/tmp/
    depends_on: #indica que primero debe subir los servicios indicados.
      - base-datos-app-usuarios
      - eurekaserver




#
  microservicio-notificaciones: #nombre del servicio
      image: enmanuelcruzdejesus/microservicio-notificaciones #imagen utilizada.
      ports: #puertos que estaran expuestos.
        - 8282:8282
      environment: #variable de ambiente
        - server.port=8282
        - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka
      networks: #red para conectar los equipos.
        - main-net
      volumes:
        - my-vol:/tmp/
      depends_on: #indica que primero debe subir los servicios indicados.
        - eurekaserver



networks:
  main-net:

#networks:  #bloque para las redes
#  main-net:   #indicando la red definida

volumes: #Bloque para definir los volumenes
  my-vol:
